version: '3.7'

services:
  web:
    restart: always
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./user/.:/core
    ports:
      - 8051:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


volumes:
  postgres_data: